src: don't crash on invalid script positions
This "fixes" the crash reported in #422, in the sense that you no longer
get a crash. However the printing does not actually work, i.e. you
currently get an error like this:

```console
(lldb) v8 i -s 0x2196b1a09a29
error: Invalid source range, start_pos=3108, len=-3098, source_len=10
```

I'm deeming this better than crashing. We should really never be
crashing as the coredump might be incomplete/partially corrupted.
(Also, we already know function printing on v16 doesn't work right now.)